version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped 